pipeline{
    agent any
    
    stages{
        stage('build'){
            steps{
                sh 'echo build is successful'
                
            }
        }
        stage('deploy'){
            steps{
                sh "echo deploy is successfull {hostname}"
            }
        }
            
        }

