pipeline{
    agent any
    
    stages{
        stage('build'){
            steps{
                sh 'echo Build is successful'
            }
        }
    stage('deploy'){
            steps{
                sh 'echo deploy calling from ${JOB_NAME}'
            }
        }
}

}

