pipeline{
    agent any
    
    stages{
        stage('build'){
            steps{
                sh 'echo Build is successful'
            }
        }
        stage ('deploy'){
            steps{
                sh 'echo deploy is now sucessfull'
                }
        }    

    }
}
